### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by haoai-1997** [1069066484/PanoSwinTransformerObjectDetection#1]
Hello, this code is the implementation of  “PanoSwin: a Pano-style Swin Transformer for Panorama Understanding  (CVPR 2023)”?

**Comment by 1069066484** [comment]
Yes, thanks for your concern.  I am recently busy with things like my jobs and my graduation. I'm going to release training configurations as soon as possible (maybe in one month or two).

**Comment by haoai-1997** [comment]
Okay， Thanks very much, have a good time!
